# Generated by Django 2.1.5 on 2019-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190312_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorflame',
            name='breakup_date',
            field=models.DateField(verbose_name='Breakup Date'),
        ),
        migrations.AlterField(
            model_name='priorflame',
            name='relationship_duration',
            field=models.IntegerField(verbose_name='Together for'),
        ),
    ]
