# Generated by Django 2.1.5 on 2019-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190312_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealbreaker',
            name='bachelor',
        ),
        migrations.AddField(
            model_name='bachelor',
            name='dealbreakers',
            field=models.ManyToManyField(to='main_app.Dealbreaker'),
        ),
        migrations.AlterField(
            model_name='priorflame',
            name='relationship_duration',
            field=models.IntegerField(verbose_name='Together for (in months)'),
        ),
    ]
